# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oobq7KbcOlibmnTn8JAVeDnJ3CY2m6bu
"""

# PYTHON DÖNEM ÖDEVİ 1. KISIM

import math
from datetime import datetime

# 1. Döngüler ve Listeler: 6 farklı müşterinin olduğu ana liste
musteriler_listesi = [
    {"ad": "Medine", "Soyad": "Hırçın", "aylik_ucret": 470, "sadakat_ayi": 14, "aktif": False},
    {"ad": "Ali", "Soyad": "Yılmaz", "aylik_ucret": 450, "sadakat_ayi": 12, "aktif": True},
    {"ad": "Ayşe", "Soyad": "Çetin", "aylik_ucret": 600, "sadakat_ayi": 36, "aktif": False},
    {"ad": "Mehmet", "Soyad": "Kara", "aylik_ucret": 300, "sadakat_ayi": 5, "aktif": True},
    {"ad": "Fatma", "Soyad": "Kılıç", "aylik_ucret": 750, "sadakat_ayi": 28, "aktif": True},
    {"ad": "Can", "Soyad": "Taşcı", "aylik_ucret": 150, "sadakat_ayi": 48, "aktif": False}
]

# 2. Fonksiyon Tanımlama: KDV ekleme
def tutar_hesapla(aylik_ucret, kdv_orani):
    # Parametre alır ve KDV eklenmiş tutarı döndürür
    toplam_tutar = aylik_ucret * (1 + kdv_orani)
    return toplam_tutar

# 3. Set Kullanımı: Benzersiz hizmet listesi
verilen_hizmetler = ["İnternet", "TV", "İnternet", "Mobil", "TV", "Güvenlik"]

# Tekrar eden hizmetleri temizle
benzersiz_hizmetler = set(verilen_hizmetler)
print(f"Benzersiz Hizmetler: {benzersiz_hizmetler}")

# Kullanıcıdan KDV oranı alma
kullanici_kdv = float(input("Lütfen uygulanacak KDV oranını girin (Örn: %20 için 20): "))
kdv_orani = kullanici_kdv / 100

# 4. Ana İşlem Döngüsü
print("\n--- MÜŞTERİ FATURA ANALİZ RAPORU ---")

toplam_fatura = 0

for musteri in musteriler_listesi:

    # KDV'li tutarı hesapla
    kdvli_tutar = tutar_hesapla(musteri["aylik_ucret"], kdv_orani)

    # Toplam tutarı yukarı yuvarla
    yuvarlanmis_tutar = math.ceil(kdvli_tutar)

    toplam_fatura += yuvarlanmis_tutar

    # Churn Analizi
    durum = "Aktif" if musteri["aktif"] else "Ayrılma Riskinde (Churn)"

    print(
        f"Müşteri: {musteri['ad']} {musteri['Soyad']} | "
        f"Fatura: {yuvarlanmis_tutar} TL | "
        f"Durum: {durum}"
    )

# Güncel tarih ekleme
guncel_tarih = datetime.now().strftime("%d/%m/%Y %H:%M")

print(f"\nToplam Tahsil Edilecek Tutar: {toplam_fatura} TL")
print(f"Rapor Tarihi: {guncel_tarih}")

# PYTHON DÖNEM ÖDEVİ 2. KISIM

import datetime  # Kütüphane Kullanımı: Tarih işlemleri için datetime dahil edildi
import math  # Kütüphane Kullanımı: Yuvarlama işlemleri için math dahil edildi

# Döngüler ve Listeler: 5 farklı müşterinin sözlük verilerini içeren ana liste oluşturuldu
musteriler_listesi = [
    {
        "ad": "Ali",
        "ucret": 450,
        "hizmet": "İnternet",
        "aktif": True,
        "skor": 85,
    },
    {
        "ad": "Ayşe",
        "ucret": 600,
        "hizmet": "Televizyon",
        "aktif": False,
        "skor": 40,
    },
    {
        "ad": "Mehmet",
        "ucret": 300,
        "hizmet": "İnternet",
        "aktif": True,
        "skor": 90,
    },
    {
        "ad": "Fatma",
        "ucret": 750,
        "hizmet": "Telefon",
        "aktif": True,
        "skor": 55,
    },
    {
        "ad": "Can",
        "ucret": 150,
        "hizmet": "Televizyon",
        "aktif": True,
        "skor": 30,
    },

]



# Hata Denetimi ve Set Kullanımı: Şirketin verdiği tüm hizmetler için boş liste tanımlandı
tum_hizmetler = []


# Fonksiyon Tanımlama: Aylık ücrete %20 KDV ekleyen fonksiyon yazıldı
def tutar_hesapla(aylik_ucret):
    try:  # Hata Denetimi ve Set Kullanımı: Sayısal veri kontrolü için try bloğu açıldı
        kdvli_tutar = (
            aylik_ucret * 1.20
        )  # Fonksiyon Tanımlama: %20 KDV hesaplaması yapıldı
        return kdvli_tutar  # Fonksiyon Tanımlama: Hesaplanan değer geri döndürüldü
    except TypeError:  # Hata Denetimi ve Set Kullanımı: Hatalı veri tipi yakalandı
        print("Hata: Ücret bilgisi sayısal olmalıdır.")  # Hata Denetimi ve Set Kullanımı: Kullanıcıya hata mesajı basıldı
        return 0  # Hata Denetimi ve Set Kullanımı: Hata durumunda 0 döndürüldü


# Döngüler ve Listeler: Müşteri listesini dönmek için for döngüsü başlatıldı
for musteri in musteriler_listesi:



    # Hata Denetimi ve Set Kullanımı: Müşterinin hizmeti listeye eklendi
    tum_hizmetler.append(musteri["hizmet"])



    # Fonksiyon Tanımlama: KDV'li tutarı hesaplamak için fonksiyon çağrıldı
    ham_tutar = tutar_hesapla(musteri["ucret"])

    # Kütüphane Kullanımı: Toplam fatura tutarı math.ceil ile yukarıya yuvarlandı
    final_tutari = math.ceil(ham_tutar)

    # Döngüler ve Listeler: Müşteri fatura detayları ekrana yazdırıldı
    print(f"Müşteri: {musteri['ad']} - Fatura: {final_tutari} TL")

    # AI Denetimi: Churn riski tespiti için mantıksal sorgu başlatıldı
    if not musteri["aktif"] or musteri["skor"] < 50:
        # AI Denetimi: Churn riski taşıyan müşteriler ekrana basıldı
        print(f"--> UYARI: {musteri['ad']} isimli müşteri Churn riskindedir!")

# Hata Denetimi ve Set Kullanımı: Set() fonksiyonu ile benzersiz hizmetler filtrelendi
benzersiz_hizmetler = set(tum_hizmetler)

# Hata Denetimi ve Set Kullanımı: Benzersiz hizmet listesi ekrana basıldı
print(f"\nBenzersiz Hizmet Listemiz: {benzersiz_hizmetler}")
  #print(f"\nBenzersiz Hizmet Listemiz: ",benzersiz_hizmetler)

# Kütüphane Kullanımı: Datetime kütüphanesi ile bugünün tarihi alındı
bugun = datetime.datetime.now().strftime("%d.%m.%Y")

# Kütüphane Kullanımı: Günün tarihi faturanın en altına eklendi
print(f"Fatura Düzenleme Tarihi: {bugun}")